# Netlify configuration for sparker888.com with portal subdomain

[build]
  publish = ".next"
  command = "npm run build"

# Redirect rules for portal subdomain routing
[[redirects]]
  from = "/portal/*"
  to = "/portal/:splat"
  status = 200

# SPA redirect for any unmatched routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Accept = "text/html"}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Portal-specific headers
[[headers]]
  for = "/portal/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=0, must-revalidate"

# Static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"