import { Container } from '@/components/Container'
import { SimpleLayout } from '@/components/SimpleLayout'
import Link from 'next/link'

function CheckIcon(props) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <polyline points="20,6 9,17 4,12" />
    </svg>
  )
}

function RocketIcon(props) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  )
}

function LightningIcon(props) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <polygon points="13,2 3,14 12,14 11,22 21,10 12,10" />
    </svg>
  )
}

function TimerIcon(props) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <circle cx="12" cy="12" r="10" />
      <polyline points="12,6 12,12 16,14" />
    </svg>
  )
}

const processSteps = [
  {
    week: 'Week 1',
    title: 'Discovery & Architecture',
    description: 'We validate your idea, define core features, and create the technical architecture using modern tools.',
    deliverables: [
      'Market validation research',
      'Feature prioritization matrix',
      'Technical architecture plan',
      'Design system foundation'
    ]
  },
  {
    week: 'Week 2',
    title: 'Core Development',
    description: 'Using AI-assisted development, we build the MVP with essential features for user testing.',
    deliverables: [
      'Functional MVP with core features',
      'User authentication system',
      'Database design & implementation',
      'Responsive UI framework'
    ]
  },
  {
    week: 'Week 3',
    title: 'Enhancement & Testing',
    description: 'Add advanced features, integrate payments/analytics, and conduct thorough testing.',
    deliverables: [
      'Payment system integration',
      'Analytics & tracking setup',
      'Performance optimization',
      'Cross-device testing'
    ]
  },
  {
    week: 'Week 4',
    title: 'Launch & Validation',
    description: 'Deploy your prototype, gather user feedback, and plan next steps based on real data.',
    deliverables: [
      'Production deployment',
      'User feedback collection',
      'Analytics dashboard setup',
      'Growth strategy recommendations'
    ]
  }
]

const technologies = [
  {
    name: 'Claude Code',
    description: 'AI-powered development for 4x faster coding',
    logo: '🤖'
  },
  {
    name: 'Astro',
    description: 'Ultra-fast web framework for optimal performance',
    logo: '🚀'
  },
  {
    name: 'Next.js',
    description: 'Production-ready React applications',
    logo: '⚛️'
  },
  {
    name: 'Tailwind CSS',
    description: 'Rapid UI development with consistent design',
    logo: '🎨'
  },
  {
    name: 'Stripe',
    description: 'Payment processing for immediate monetization',
    logo: '💳'
  },
  {
    name: 'Vercel',
    description: 'Zero-config deployment and hosting',
    logo: '▲'
  }
]

const successMetrics = [
  {
    metric: '30 Days',
    description: 'From idea to functional prototype',
    icon: TimerIcon
  },
  {
    metric: '4x Faster',
    description: 'Development speed with AI assistance',
    icon: LightningIcon
  },
  {
    metric: '$30K+',
    description: 'Revenue generated by MPM in first quarter',
    icon: RocketIcon
  }
]

function ProcessStep({ step, index }) {
  return (
    <div className="relative">
      {/* Timeline connector */}
      {index < processSteps.length - 1 && (
        <div className="absolute left-6 top-16 w-0.5 h-24 bg-gradient-to-b from-amber-500 to-sky-500"></div>
      )}
      
      <div className="flex gap-4">
        <div className="flex-shrink-0">
          <div className="flex items-center justify-center w-12 h-12 font-bold text-white rounded-full bg-gradient-to-br from-amber-500 to-sky-500">
            {index + 1}
          </div>
        </div>
        
        <div className="flex-1 pb-8">
          <div className="mb-2">
            <span className="text-sm font-semibold text-amber-600 dark:text-amber-400">
              {step.week}
            </span>
          </div>
          <h3 className="mb-3 text-xl font-bold text-slate-900 dark:text-slate-100">
            {step.title}
          </h3>
          <p className="mb-4 text-slate-600 dark:text-slate-400">
            {step.description}
          </p>
          
          <div className="space-y-2">
            {step.deliverables.map((deliverable) => (
              <div key={deliverable} className="flex items-center gap-2">
                <CheckIcon className="flex-shrink-0 w-4 h-4 text-green-500" />
                <span className="text-sm text-slate-700 dark:text-slate-300">
                  {deliverable}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

function TechnologyCard({ tech }) {
  return (
    <div className="p-4 transition-colors bg-white border rounded-lg border-slate-200 dark:border-slate-700 dark:bg-slate-800 hover:border-amber-300 dark:hover:border-amber-600">
      <div className="flex items-center gap-3 mb-2">
        <span className="text-2xl">{tech.logo}</span>
        <h3 className="font-semibold text-slate-900 dark:text-slate-100">
          {tech.name}
        </h3>
      </div>
      <p className="text-sm text-slate-600 dark:text-slate-400">
        {tech.description}
      </p>
    </div>
  )
}

function MetricCard({ metric }) {
  const IconComponent = metric.icon
  
  return (
    <div className="p-6 text-center border rounded-xl bg-gradient-to-br from-amber-50 to-sky-50 dark:from-amber-900/20 dark:to-sky-900/20 border-amber-200 dark:border-amber-800">
      <div className="flex justify-center mb-4">
        <div className="p-3 rounded-full bg-gradient-to-br from-amber-500 to-sky-500">
          <IconComponent className="w-6 h-6 text-white" />
        </div>
      </div>
      <div className="mb-2 text-3xl font-bold text-slate-900 dark:text-slate-100">
        {metric.metric}
      </div>
      <p className="text-slate-600 dark:text-slate-400">
        {metric.description}
      </p>
    </div>
  )
}

export const metadata = {
  title: 'Light. Speed. Prototypes - Validate Your Solopreneur Ideas in 30 Days',
  description: 'AI-assisted rapid development for bootstrapped entrepreneurs. From idea to functional prototype in 30 days using modern tools and proven processes.',
}

export default function LightSpeedPrototypes() {
  return (
    <SimpleLayout
      title="Light. Speed. Prototypes ⚡"
      intro="Validate Your Solopreneur Ideas in 30 Days"
    >
      {/* Hero Section */}
      <div className="mb-16">
        <div className="max-w-4xl mx-auto text-center">
          <p className="mb-8 text-xl text-slate-600 dark:text-slate-400">
            Fellow solopreneur, stop building products nobody wants. Get a functional prototype 
            in 30 days, validate with real users, then scale what works.
          </p>
          
          <div className="grid grid-cols-1 gap-6 mb-12 md:grid-cols-3">
            {successMetrics.map((metric) => (
              <MetricCard key={metric.metric} metric={metric} />
            ))}
          </div>
          
          <div className="p-8 text-white bg-gradient-to-r from-amber-500 to-sky-500 rounded-2xl">
            <h2 className="mb-4 text-2xl font-bold">
              🎯 The MPM Success Story
            </h2>
            <p className="mb-6 text-lg opacity-90">
              Midjourney Prompt Manager went from idea to $30K+ quarterly revenue in 30 days of development. 
              This same AI-assisted process can work for your solopreneur venture.
            </p>
            <Link
              href="https://midjourneypromptmanager.com/"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-block px-6 py-3 font-semibold transition-colors bg-white rounded-lg text-amber-600 hover:bg-amber-50"
            >
              See MPM Live →
            </Link>
          </div>
        </div>
      </div>

      {/* 30-Day Process */}
      <section className="mb-16">
        <div className="mb-12 text-center">
          <h2 className="mb-4 text-3xl font-bold text-slate-900 dark:text-slate-100">
            The 30-Day Validation Process
          </h2>
          <p className="max-w-3xl mx-auto text-lg text-slate-600 dark:text-slate-400">
            Using AI-assisted development and proven solopreneur methodology, 
            we compress 4 months of traditional development into 30 days.
          </p>
        </div>
        
        <div className="max-w-3xl mx-auto">
          {processSteps.map((step, index) => (
            <ProcessStep key={step.week} step={step} index={index} />
          ))}
        </div>
      </section>

      {/* Technology Stack */}
      <section className="mb-16">
        <div className="mb-12 text-center">
          <h2 className="mb-4 text-3xl font-bold text-slate-900 dark:text-slate-100">
            Modern Tools for Maximum Speed
          </h2>
          <p className="max-w-3xl mx-auto text-lg text-slate-600 dark:text-slate-400">
            The same technology stack I used to build MPM, optimized for rapid prototyping 
            and easy scaling for bootstrapped entrepreneurs.
          </p>
        </div>
        
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {technologies.map((tech) => (
            <TechnologyCard key={tech.name} tech={tech} />
          ))}
        </div>
      </section>

      {/* Perfect For Section */}
      <section className="mb-16">
        <div className="mb-12 text-center">
          <h2 className="mb-4 text-3xl font-bold text-slate-900 dark:text-slate-100">
            Perfect for Bootstrapped Solopreneurs Who...
          </h2>
        </div>
        
        <div className="grid max-w-4xl grid-cols-1 gap-8 mx-auto md:grid-cols-2">
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <CheckIcon className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
              <div>
                <h3 className="font-semibold text-slate-900 dark:text-slate-100">Have a clear idea but need validation</h3>
                <p className="text-sm text-slate-600 dark:text-slate-400">You know what you want to build but need to test it with real users before investing months of development.</p>
              </div>
            </div>
            
            <div className="flex items-start gap-3">
              <CheckIcon className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
              <div>
                <h3 className="font-semibold text-slate-900 dark:text-slate-100">Want to launch before competitors</h3>
                <p className="text-sm text-slate-600 dark:text-slate-400">Speed to market matters. Get your MVP live while others are still planning.</p>
              </div>
            </div>
            
            <div className="flex items-start gap-3">
              <CheckIcon className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
              <div>
                <h3 className="font-semibold text-slate-900 dark:text-slate-100">Need technical expertise temporarily</h3>
                <p className="text-sm text-slate-600 dark:text-slate-400">You're business-focused but need a technical partner for the initial build.</p>
              </div>
            </div>
          </div>
          
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <CheckIcon className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
              <div>
                <h3 className="font-semibold text-slate-900 dark:text-slate-100">Value cost-effective development</h3>
                <p className="text-sm text-slate-600 dark:text-slate-400">AI-assisted development means lower costs and faster delivery than traditional agencies.</p>
              </div>
            </div>
            
            <div className="flex items-start gap-3">
              <CheckIcon className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
              <div>
                <h3 className="font-semibold text-slate-900 dark:text-slate-100">Want ownership and control</h3>
                <p className="text-sm text-slate-600 dark:text-slate-400">You get full source code, documentation, and hosting setup to maintain control of your product.</p>
              </div>
            </div>
            
            <div className="flex items-start gap-3">
              <CheckIcon className="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
              <div>
                <h3 className="font-semibold text-slate-900 dark:text-slate-100">Plan to scale beyond MVP</h3>
                <p className="text-sm text-slate-600 dark:text-slate-400">Built on scalable architecture that grows with your business success.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <div className="p-8 mt-16 border bg-slate-50 dark:bg-slate-800/50 rounded-2xl border-slate-200 dark:border-slate-700">
        <div className="text-center">
          <h2 className="mb-4 text-2xl font-bold text-slate-900 dark:text-slate-100">
            Ready to Validate Your Idea?
          </h2>
          <p className="max-w-2xl mx-auto mb-6 text-lg text-slate-600 dark:text-slate-400">
            Let's discuss your project and see if Light. Speed. Prototypes is the right fit. 
            I only take on projects I'm confident will succeed.
          </p>
          <div className="flex flex-col justify-center gap-4 sm:flex-row">
            <Link
              href="/contact"
              className="inline-flex items-center gap-2 px-8 py-4 font-semibold text-white transition-colors rounded-lg bg-gradient-to-r from-amber-500 to-sky-500 hover:from-amber-600 hover:to-sky-600"
            >
              <RocketIcon className="w-5 h-5" />
              Start Your 30-Day Prototype
            </Link>
            <Link
              href="/articles/light-speed-6"
              className="inline-flex items-center gap-2 px-8 py-4 font-semibold transition-colors rounded-lg bg-slate-200 dark:bg-slate-700 text-slate-700 dark:text-slate-200 hover:bg-slate-300 dark:hover:bg-slate-600"
            >
              Read the MPM Case Study
            </Link>
          </div>
        </div>
      </div>
    </SimpleLayout>
  )
}